Repository 4ForWin/flutter-football-sns, pull requests merged in 2025-05, with the labels that each got.

#10 [Splash] 스플래시 화면 구현
  .metadata
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Bold.otf
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Regular.otf
  lib/main.dart
  lib/presentation/view/login/login_view.dart
  lib/presentation/view/splash/splash_view.dart
  pubspec.yaml
  test/widget_test.dart
Labels: feat

#7 Hyunjin912/issue1
  assets/icons/keep.svg
  assets/icons/request.svg
  assets/icons/skip.svg
  lib/main.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/home/view_models/feed_view_model.dart
  lib/presentation/pages/home/view_models/home_bottom_navigation_bar_view_model.dart
  lib/presentation/pages/home/widgets/home_bottom_navigation_bar.dart
  lib/presentation/pages/home/widgets/home_indexed_stack.dart
  lib/presentation/pages/home/widgets/mercenary_search_tab.dart
  lib/presentation/pages/home/widgets/state_icons.dart
  lib/presentation/pages/home/widgets/team_sarch_tab.dart
  pubspec.yaml
Labels: feat

#9 feat: settingpage UI구성, MVVM 모델 구성
  lib/main.dart
  lib/presentation/pages/setting/alarm_setting_page.dart
  lib/presentation/pages/setting/setting_page.dart
  lib/presentation/pages/setting/viewmodel/alarm_setting_view_model.dart
  lib/presentation/pages/setting/viewmodel/setting_view_model.dart
  lib/presentation/pages/setting/widget/profile_section.dart
  lib/presentation/pages/setting/widget/setting_tile.dart
Labels: feat

#13 Monho/issue12
  assets/images/kakao_login.svg
  lib/main.dart
  lib/presentation/pages/login/login_view.dart
  lib/presentation/pages/splash/splash_view.dart
  pubspec.yaml
Labels: feat

#14 <feat>: <Write UI 구현>
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/write.dart/write_page.dart
Labels: feat

#17 feat: Settingpage 라우팅연결, policy_page 추가
  lib/main.dart
  lib/presentation/pages/setting/alarm_setting_page.dart
  lib/presentation/pages/setting/policy_page.dart
  lib/presentation/pages/setting/setting_page.dart
  lib/presentation/pages/setting/viewmodel/setting_view_model.dart
  lib/presentation/pages/setting/widget/profile_section.dart
  test/widget_test.dart
Labels: feat

#18 [Intro] 인트로 페이지 구현
  .DS_Store
  assets/.DS_Store
  assets/images/finding_team.svg
  assets/images/recruiting_player.svg
  lib/.DS_Store
  lib/main.dart
  lib/presentation/.DS_Store
  lib/presentation/pages/intro/intro_level_page.dart
  lib/presentation/pages/intro/intro_type_page.dart
  lib/presentation/pages/intro/view_models/intro_level_view_model.dart
  lib/presentation/pages/intro/widgets/progress_bar.dart
  lib/presentation/pages/intro/widgets/text_label.dart
  pubspec.yaml
Labels: feat

#20 Hyunjin912/issue15
  .gitignore
  android/app/build.gradle.kts
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  firebase.json
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/core/geolocator_helper.dart
  lib/data/data_source/feed_data_source.dart
  lib/data/data_source/feed_data_source_impl.dart
  lib/data/data_source/image_data_source.dart
  lib/data/data_source/image_data_source_impl.dart
  lib/data/data_source/location_data_source.dart
  lib/data/data_source/location_data_source_impl.dart
  lib/data/dto/feed_dto.dart
  lib/data/repository/feed_repository_impl.dart
  lib/data/repository/image_repository_impl.dart
  lib/data/repository/location_repository_impl.dart
  lib/domain/entity/feed.dart
  lib/domain/repository/feed_repository.dart
  lib/domain/repository/image_repository.dart
  lib/domain/repository/location_repository.dart
  lib/domain/usecase/fetch_feeds_usecase.dart
  lib/domain/usecase/get_location_usecase.dart
  lib/domain/usecase/insert_feed_usecase.dart
  lib/domain/usecase/upload_image_usecase.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/presentation/pages/home/view_models/feed_view_model.dart
  lib/presentation/pages/home/widgets/team_sarch_tab.dart
  lib/presentation/pages/providers.dart
  lib/presentation/pages/write.dart/write_page.dart
  lib/presentation/pages/write.dart/write_view_model.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.yaml
  test/data/feed_data_source_test.dart
  test/data/feed_dto_test.dart
  test/dummy/feed_dto.json
Labels: feat

#22 <refactor>: <Write 페이지 위젯 분리>
  lib/core/loading_bar.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/write.dart/widgets/content_text_form_field.dart
  lib/presentation/pages/write.dart/widgets/image_bottom_sheet.dart
  lib/presentation/pages/write.dart/widgets/image_viewer.dart
  lib/presentation/pages/write.dart/widgets/location_icon.dart
  lib/presentation/pages/write.dart/widgets/location_text_form_field.dart
  lib/presentation/pages/write.dart/widgets/post_button.dart
  lib/presentation/pages/write.dart/widgets/team_text_form_field.dart
  lib/presentation/pages/write.dart/widgets/title_text_form_field.dart
  lib/presentation/pages/write.dart/write_page.dart
Labels: refactor

#31 Monho/issue25
  lib/presentation/pages/terms/widget/terms_page.dart
  pubspec.yaml
Labels: feat

#32 Monho/issue27
  lib/core/shared_prefs/shared_prefs.dart
  lib/main.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/login/view_models/kakao_login_viewmodel.dart
  lib/presentation/pages/splash/splash_view.dart
  lib/presentation/pages/terms/widget/terms_page.dart
Labels: feat

#35 [Setting] 세팅페이지 색상, 이용약관 연결
  lib/main.dart
  lib/presentation/pages/setting/alarm_setting_page.dart
  lib/presentation/pages/setting/policy_page.dart
  lib/presentation/pages/setting/setting_page.dart
  lib/presentation/pages/setting/viewmodel/setting_view_model.dart
  lib/presentation/pages/setting/widget/profile_section.dart
  lib/presentation/pages/setting/widget/setting_tile.dart
Labels: feat

#39 <feat>: <스크롤 기능 구현>
  lib/data/data_source/feed_data_source.dart
  lib/data/data_source/feed_data_source_impl.dart
  lib/data/data_source/feed_log_data_source.dart
  lib/data/data_source/feed_log_data_source_impl.dart
  lib/data/dto/feed_dto.dart
  lib/data/dto/feed_log_dto.dart
  lib/data/repository/feed_log_repository_impl.dart
  lib/data/repository/feed_repository_impl.dart
  lib/domain/entity/feed_log.dart
  lib/domain/repository/feed_log_repository.dart
  lib/domain/repository/feed_repository.dart
  lib/domain/usecase/add_user_to_list_usecase.dart
  lib/domain/usecase/fetch_feed_logs_usecase.dart
  lib/domain/usecase/fetch_feeds_usecase.dart
  lib/domain/usecase/insert_feed_log_usecase.dart
  lib/presentation/pages/home/view_models/feed_view_model.dart
  lib/presentation/pages/home/widgets/home_indexed_stack.dart
  lib/presentation/pages/home/widgets/team_sarch_tab.dart
  lib/presentation/pages/providers.dart
  pubspec.yaml
Labels: feat

#41 Monho/issue34
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  lib/core/notification_service/notification_service.dart
  lib/main.dart
  lib/presentation/pages/login/view_models/kakao_login_viewmodel.dart
  lib/presentation/pages/setting/widget/profile_section.dart
  pubspec.yaml
Labels: feat

#43 [Setting] 신청내역 페이지 추가(더미데이터 추가), 카카오 이메일 삭제 Fixes#38
  lib/data/data_source/mercenary_apply_history_data_source.dart
  lib/data/data_source/mercenary_apply_history_data_source_impl.dart
  lib/data/data_source/team_apply_history_data_source.dart
  lib/data/data_source/team_apply_history_data_source_impl.dart
  lib/data/dto/mercenary_apply_history_dto.dart
  lib/data/dto/team_apply_history_dto.dart
  lib/data/repository/mercenary_apply_history_repository_impl.dart
  lib/data/repository/team_apply_history_repository_impl.dart
  lib/domain/entity/mercenary_apply_history.dart
  lib/domain/entity/team_apply_history.dart
  lib/domain/repository/mercenary_apply_history_repository.dart
  lib/domain/repository/team_apply_history_repository.dart
  lib/domain/usecase/cancel_mercenary_apply_usecase.dart
  lib/domain/usecase/fetch_mercenary_apply_histories_usecase.dart
  lib/domain/usecase/fetch_team_apply_histories_usecase.dart
  lib/domain/usecase/update_team_apply_status_usecase.dart
  lib/main.dart
  lib/presentation/pages/mercenary_apply_history/mercenary_apply_history_item.dart
  lib/presentation/pages/mercenary_apply_history/mercenary_apply_history_page.dart
  lib/presentation/pages/mercenary_apply_history/mercenary_apply_history_view_model.dart
  lib/presentation/pages/providers.dart
  lib/presentation/pages/setting/alarm_setting_page.dart
  lib/presentation/pages/setting/setting_page.dart
  lib/presentation/pages/setting/viewmodel/setting_view_model.dart
  lib/presentation/pages/setting/widget/profile_section.dart
  lib/presentation/pages/team_apply_history/team_apply_history_item.dart
  lib/presentation/pages/team_apply_history/team_apply_history_page.dart
  lib/presentation/pages/team_apply_history/team_apply_history_view_model.dart
Labels: feat

#53 [Fix] 신청페이지 최근 하나만 표시되는 버그 수정 Fixes #52
  lib/core/services/application_status_service.dart
  lib/data/data_source/my_mercenary_invitation_history_data_source_impl.dart
  lib/data/data_source/my_team_application_history_data_source_impl.dart
  lib/data/dto/my_mercenary_invitation_history_dto.dart
  lib/data/dto/my_team_application_history_dto.dart
Labels: bug

#57 <feat>: <본인 피드 필터링>
  lib/data/data_source/mercenary_feed_data_source_impl.dart
  lib/data/data_source/team_feed_data_source_impl.dart
Labels: feat

#56 [Fix] 알림설정 토글 수정, 위치정보 리턴값 수정 Fixes #55
  lib/data/data_source/location_data_source_impl.dart
  lib/main.dart
  lib/presentation/pages/setting/alarm_setting_page.dart
  lib/presentation/pages/setting/setting_page.dart
  lib/presentation/pages/setting/viewmodel/alarm_setting_view_model.dart
Labels: fix
